remote_theme: pages-themes/slate@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Mi portafolio
#description: [A short description of your site's purpose]

github:
  another_url: ./_layouts/contact.html